 /*Sample Create ---*/
Create table Guest
(
GUEST_NO CHAR(8) PRIMARY KEY,
LAST_NAME VARCHAR2(30),
FIRST_NAME VARCHAR2(30),
DOB DATE,
SEX CHAR(1),
HOME_PHONE VARCHAR2(20),
WORK_PHONE VARCHAR2(20),
FAX VARCHAR2(20),
ADDRESS VARCHAR2(40),
SUBURB VARCHAR2(40),
STATE VARCHAR2(40),
POSTCODE NUMBER(4)
)

/*Sample - insert values */
Insert into Guest 
(GUEST_NO,LAST_NAME,FIRST_NAME,DOB,SEX,HOME_PHONE,
ADDRESS,SUBURB,STATE,POSTCODE)
values
('G0000001', 'Smith', 'John','21-jan-01','M','8765423',
'Elgar Road','Burwood','VIC',3125);

Insert into Guest 
(GUEST_NO,LAST_NAME,FIRST_NAME,DOB,SEX,HOME_PHONE,FAX,
ADDRESS,SUBURB,STATE,POSTCODE)
values
('G0000002', 'John', 'Amy','25-Feb-02','F','8765423',
'45678901',
'Elgar Road','Burwood','VIC',3125);

/*Sample Delete ---*/
Delete 
FROM Guest


Delete 
FROM Guest
WHERE GUEST_NO = 'G0000002'

/*Sample Update ---*/
UPDATE GUEST
SET ADDRESS = 'Burwood Road'
WHERE GUEST_NO = 'G0000001'

/*Sample Alter ---*/
ALTER TABLE GUEST ADD INTI VARCHAR(3);
ALTER TABLE GUEST DROP COLUMN INTI;


/*WEEK 4 - LAB QUERIES ****/

A.
/*A.Show student numbers of students enrolled in 
BI918 in semester 2. */
SELECT DISTINCT PROGRAMME_CODE 
FROM STUDENT

SELECT DISTINCT COURSE_CODE 
FROM STUDENT_COURSE

SELECT DISTINCT COURSE_CODE 
FROM STUDENT_COURSE

SELECT DISTINCT  SEM_START
FROM STUDENT_COURSE
/* ANSWER */
SELECT STUDENT_NO
FROM STUDENT_COURSE
WHERE COURSE_CODE = 'BI918' AND SEM_START = 2 

B.
/* As in query A plus show the student surname 
and given name. */ 
SELECT S.STUDENT_NO, S.GIVEN,S.SURNAME
FROM STUDENT_COURSE SC, STUDENT S
WHERE SC.STUDENT_NO = S.STUDENT_NO AND  
COURSE_CODE = 'BI918' AND SEM_START = 2
/*EXPLANATION*/
SELECT S.STUDENT_NO, S.GIVEN,S.SURNAME
FROM STUDENT_COURSE SC, STUDENT S
WHERE SC.STUDENT_NO = S.STUDENT_NO AND /*JOIN CONDITION*/ 
COURSE_CODE = 'BI918' AND SEM_START = 2 /*OTHER CONDITIONS*/

C.
/* As in query B plus show the course name. */
SELECT S.STUDENT_NO, S.GIVEN,S.SURNAME, C.COURSE_NAME
FROM STUDENT_COURSE SC, STUDENT S, COURSE C
WHERE SC.STUDENT_NO = S.STUDENT_NO AND 
SC.COURSE_CODE = C.COURSE_CODE AND 
SC.COURSE_CODE = 'BI918' AND SEM_START = 2
D.
/* List student name, programme code and 
programme name for all students. */
SELECT S.GIVEN ||','|| S.SURNAME,P.PROGRAMME_CODE,
P.PROGRAMME_NAME
FROM STUDENT S, PROGRAMME P
WHERE P.PROGRAMME_CODE = S.PROGRAMME_CODE

E.
/* List the programme name of students 
enrolled in BI958 in semester 2*/

SELECT DISTINCT S.STUDENT_NO, P.PROGRAMME_NAME
FROM STUDENT S, STUDENT_COURSE SC, PROGRAMME P
WHERE S.STUDENT_NO = SC.STUDENT_NO AND 
S.PROGRAMME_CODE = P.PROGRAMME_CODE AND
SC.COURSE_CODE = 'BI958' AND SC.SEM_START = 2

F.
/* List each student number and how many 
courses the student is enrolled in 
(group by)*/
SELECT STUDENT_NO, COUNT(*)
FROM STUDENT_COURSE
GROUP BY STUDENT_NO
G.
/*List each course code and how many students are 
enrolled in each course, only 
for semester 1 (group by). */
SELECT COURSE_CODE,COUNT(*)
FROM STUDENT_COURSE
WHERE SEM_START=1
GROUP BY COURSE_CODE
H.
/*As in query G but also show the course 
name (hint: secondary grouping field)*/
SELECT C.COURSE_CODE,C.COURSE_NAME,COUNT(*)
FROM STUDENT_COURSE SC, COURSE C
WHERE SC.COURSE_CODE= C.COURSE_CODE AND SC.SEM_START=1
GROUP BY C.COURSE_CODE, C.COURSE_NAME
I.
/*Show a list of students’ full name, age, 
and the programme name the student is 
in (using programme_code in student table)
. Show only students enrolled in the 
course AC459. */
SELECT DISTINCT SURNAME || ', ' || GIVEN AS "FULLNAME",
FLOOR((SYSDATE-DOB)/365.25), PROGRAMME_NAME
FROM STUDENT_COURSE, STUDENT, PROGRAMME
WHERE COURSE_CODE = 'AC459'
AND STUDENT_COURSE.STUDENT_NO = STUDENT.STUDENT_NO
AND PROGRAMME.PROGRAMME_CODE = STUDENT.PROGRAMME_CODE
J.
/*Alter the query done in I. to show only students older 
than 30 years of age. */

SELECT DISTINCT SURNAME || ',' || GIVEN AS FULLNAME,
FLOOR((SYSDATE - DOB)/365.25), PROGRAMME_NAME
FROM STUDENT_COURSE, STUDENT, PROGRAMME
WHERE COURSE_CODE = 'AC459'
AND STUDENT_COURSE.STUDENT_NO = STUDENT.STUDENT_NO
AND PROGRAMME.PROGRAMME_CODE = STUDENT.PROGRAMME_CODE
AND ((SYSDATE - DOB)/365.25) > 30;





